// <auto-generated />
namespace RafflesChart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class schemechanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(schemechanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201409281254048_schemechanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
